### ISSUE TITLE
Functional Tests 3.4 API Tests

### ISSUE THREAD

**Issue by jordanzyx** [WSUCptSCapstone-Fall2022Spring2023/msft-imagedataprocessing#134]
https://github.com/WSUCptSCapstone-Fall2022Spring2023/msft-imagedataprocessing/issues/125
https://github.com/WSUCptSCapstone-Fall2022Spring2023/msft-imagedataprocessing/issues/124
https://github.com/WSUCptSCapstone-Fall2022Spring2023/msft-imagedataprocessing/issues/123
https://github.com/WSUCptSCapstone-Fall2022Spring2023/msft-imagedataprocessing/issues/122
https://github.com/WSUCptSCapstone-Fall2022Spring2023/msft-imagedataprocessing/issues/121

https://gyazo.com/fa96567f940c542adba80dcfe3e7a98d
https://gyazo.com/14a729453b6c9fefa3e6460bce7bbe47
https://gyazo.com/0c8aecedfb7dc0793190bda3a83e1594

@zach6215 view these links and close this issue if you see that the documentation is fit. I will close the child issues after.

**Comment by zach6215** [comment]
Good job
