### ISSUE TITLE
Non-Functional Tests ALL

### ISSUE THREAD

**Issue by jordanzyx** [WSUCptSCapstone-Fall2022Spring2023/msft-imagedataprocessing#135]
https://github.com/WSUCptSCapstone-Fall2022Spring2023/msft-imagedataprocessing/issues/129
https://github.com/WSUCptSCapstone-Fall2022Spring2023/msft-imagedataprocessing/issues/128
https://github.com/WSUCptSCapstone-Fall2022Spring2023/msft-imagedataprocessing/issues/127
https://github.com/WSUCptSCapstone-Fall2022Spring2023/msft-imagedataprocessing/issues/126

https://gyazo.com/bfc62cd40069fb9f3eedc8bc66f325dd
https://gyazo.com/986672cd91ab955ec1b5a678f99ce109

@zach6215 View links and close this issue. Then I will close the child issues.

**Comment by zach6215** [comment]
Good job
